services:
  postgres:
    image: postgres:15
    container_name: outbox-postgres
    environment:
      POSTGRES_DB: outbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  outbox-api:
    build:
      context: ../../
      dockerfile: apps/outbox-api/Dockerfile
    container_name: outbox-api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: outbox
      DB_SSLMODE: disable
      PORT: 8080
      WEBHOOK_URL: http://host.docker.internal:3000/webhook
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
