basePath: /
host: localhost:8081
info:
  contact: {}
  description: Provides health checks and Prometheus metrics.
  title: Metrics API
  version: "0.1"
paths:
  /health:
    get:
      description: Returns OK if service is alive
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Liveness probe
      tags:
      - health
  /ready:
    get:
      description: Checks dependencies like Postgres/Redis
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "503":
          description: Service Unavailable
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Readiness probe
      tags:
      - health
swagger: "2.0"
